### ISSUE TITLE
Chain rule memory leak

### ISSUE THREAD

**Issue by GongSiqiu** [jakeffbulmer/gbs#1]
Hello!
Your Chain rule algorithm and code are great! However, I meet a trouble when I generate a large number of samples with Chain rule algorithm. It will use up my memory even if I generate 40000 samples and save it per cycle.

```
count=40000
sim=np.empty((mode,count),dtype=np.int8) 
for j in range(1,10):
    i=0
    for sample in get_samples_click(np.array([0]*len(cov)),cov, n_samples=count):
        sim[i]=sample
        i+=1
    np.save("CR 30mode 40000-"+str(j),sim)
```
It will use up my memory after about 5 cycles

**Comment by jakeffbulmer** [comment]
Thanks for using the code! 

I have not seen any memory leak in my own use, including when running on 1 million samples. It's hard for me to diagnose the issue without seeing the rest of the code you are using and without seeing the error message. Could you send those too? Also, I think your code should read "sim[:,i] = sample" not "sim[i] = sample".

My guess is that the memory overflow is happening within numba. You can try to make sure you are using the latest version. You could also try commenting out the numba decorators on the functions in my code. This will slow things down a lot, but it would be interesting to see if the leak still occurs.

**Comment by GongSiqiu** [comment]
Thanks for your reply!
There is a typo and the second line of my code is `sim=np.empty((count,mode),dtype=np.int8) `
The rest of the code is just used to calculate the `cov` 
I have tried upgrade the numba to the latest version and the problem still exists. Maybe I can use bash to run it several times rather than use python directly when generate a large number of samples. 
The error message is here
> Error 02:49:39: Disposing session as kernel process died ExitCode: undefined, Reason: /home/g/miniconda3/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/g/miniconda3/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'f43e3b7c-e10b-4e14-b0ba-b2ca4b362fdf' instead of 'b"f43e3b7c-e10b-4e14-b0ba-b2ca4b362fdf"'.
  warn(
Info 02:49:39: Dispose Kernel process
Error 02:49:39: Raw kernel process exited code: undefined
Warn 02:49:39: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1204175)
    at /home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223227
    at Map.forEach (<anonymous>)
    at v._clearKernelState (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223212)
    at v.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1216694)
    at /home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533674
    at t.swallowExceptions (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:913059)
    at dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533652)
    at t.RawSession.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:537330)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Warn 02:49:39: Cell completed with errors Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1204175)
    at /home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223227
    at Map.forEach (<anonymous>)
    at v._clearKernelState (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223212)
    at v.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1216694)
    at /home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533674
    at t.swallowExceptions (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:913059)
    at dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533652)
    at t.RawSession.dispose (/home/g/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:537330)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Info 02:49:39: Cancel all remaining cells true || Error || undefined
Info 02:49:39: Cancel pending cells
Info 02:49:39: Cell 8 executed with state Error

**Comment by GongSiqiu** [comment]
I solved this problem by a workaround that restarting the calculation program using bash. Thanks for your help!

**Comment by jakeffbulmer** [comment]
I am still a bit confused about why this happened in the first place to be honest, and I did not manage to replicate it on my PC. Glad you found a work around! Happy to help if you encounter any other problems or questions in the future

**Comment by GongSiqiu** [comment]
The final solution is add 
```
COUNT += 1
       if COUNT % 1000 == 0:
            gc.collect()
```
to `get_samples_click`

It works well
